### ISSUE TITLE
lamindb fails when IPython is not installed

### ISSUE THREAD

**Issue by rcannood** [laminlabs/laminhub-public#29]
### Report

It turns out IPython might not always be installed, but lamindb expects that it is.

Example:

```bash
docker run --rm -it --entrypoint=bash rocker/r2u:24.04
```

Inside the docker:

```bash
apt-get update && apt-get install python3-pip python3-dev
pip install 'lamindb[aws,bionty,wetlab]>=0.77.2' --break-system-packages
lamin connect laminlabs/lamindata
python3 -c 'import lamindb'
```

Which results in:

    → connected lamindb: laminlabs/lamindata
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.12/dist-packages/lamindb/__init__.py", line 98, in <module>
        from ._view import view
      File "/usr/local/lib/python3.12/dist-packages/lamindb/_view.py", line 8, in <module>
        from IPython.display import HTML, display
    ModuleNotFoundError: No module named 'IPython'

**Comment by Koncopd** [comment]
Thank you, we will fix.

**Comment by Koncopd** [comment]
Fix is here https://github.com/laminlabs/lamindb/pull/2250
